/******************************************************************************
 * This file was generated by langium-cli 4.1.0.
 * DO NOT EDIT MANUALLY!
 ******************************************************************************/

import type { LangiumSharedCoreServices, LangiumCoreServices, LangiumGeneratedCoreServices, LangiumGeneratedSharedCoreServices, LanguageMetaData, Module } from 'langium';
import { URLSpecAstReflection } from './ast.js';
import { URLSpecGrammar } from './grammar.js';

export const URLSpecLanguageMetaData = {
    languageId: 'urlspec',
    fileExtensions: ['.urlspec'],
    caseInsensitive: false,
    mode: 'development'
} as const satisfies LanguageMetaData;

export const URLSpecGeneratedSharedModule: Module<LangiumSharedCoreServices, LangiumGeneratedSharedCoreServices> = {
    AstReflection: () => new URLSpecAstReflection()
};

export const URLSpecGeneratedModule: Module<LangiumCoreServices, LangiumGeneratedCoreServices> = {
    Grammar: () => URLSpecGrammar(),
    LanguageMetaData: () => URLSpecLanguageMetaData,
    parser: {}
};
